[package]
name = "amd_smi_lib_sys"
version = "0.2.0"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["WhiskyAKM"]
description = "bindings for amd_smi"

[dependencies]

[build-dependencies]
bindgen = "0.72.0"
